// CREATE TABLE IF NOT EXISTS posts
// (id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
// photoURL VARCHAR(255) NOT NULL,
// photographer VARCHAR(255) NOT NULL,
// uploaded_by VARCHAR(255)
// );

// CREATE TABLE IF NOT EXISTS comments
// (id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
// name VARCHAR(255) NOT NULL,
// comment VARCHAR(255) NOT NULL
// );
